//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GraphicsLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Drawing.Parsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GraphicsLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGraphicsLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] GraphicsLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] GraphicsLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] GraphicsLangParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] GraphicsLangParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] GraphicsLangParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] GraphicsLangParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] GraphicsLangParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] GraphicsLangParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] GraphicsLangParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.startDrawStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartDrawStatement([NotNull] GraphicsLangParser.StartDrawStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.drawStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrawStatement([NotNull] GraphicsLangParser.DrawStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.drawControlStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrawControlStatement([NotNull] GraphicsLangParser.DrawControlStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.colorSetStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColorSetStatement([NotNull] GraphicsLangParser.ColorSetStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] GraphicsLangParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GraphicsLangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] GraphicsLangParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] GraphicsLangParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.pointAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointAccess([NotNull] GraphicsLangParser.PointAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] GraphicsLangParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] GraphicsLangParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.pointLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointLiteral([NotNull] GraphicsLangParser.PointLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayLiteral([NotNull] GraphicsLangParser.ArrayLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.matrixLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrixLiteral([NotNull] GraphicsLangParser.MatrixLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] GraphicsLangParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphicsLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] GraphicsLangParser.TypeContext context);
}
} // namespace Drawing.Parsing
